services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    ports:
      - 8080:8080
    image: jenkins/jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
  jenkins-ui-api:
    environment:
      - JENKINS_USERNAME=fsbano
      - JENKINS_API_KEY=11c54a0aa387cd18150f1b40d7aad30649
      - JENKINS_API_BASE_URL=jenkins:8080
    container_name: jenkins-ui-api
    hostname: jenkins-ui-api
    build: jenkins-ui-api-nodejs/.
    ports:
      - 8180:8180
  jenkins-ui-dashboard-react:
    environment:
      - HOST=0.0.0.0
      - PORT=8280
      - NODE_OPTIONS=--max-old-space-size=8192
    container_name: jenkins-ui-dashboard-react
    hostname: jenkins-ui-dashboard-react
    build: jenkins-ui-dashboard-react/.
    ports:
      - 8280:8280
  jenkins-ui-dashboard-vuejs:
    container_name: jenkins-ui-dashboard-vuejs
    hostname: jenkins-ui-dashboard-vuejs
    build: jenkins-ui-dashboard-vuejs/.
    ports:
      - 8380:8380
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: keycloak/keycloak
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
